const fs = require('fs');
let content = fs.readFileSync('public/js/dashboard.js', 'utf8');
const lines = content.split('\n');
const fixedLines = [
'  mr: {',
'    dashLogoTitle: "SAARTHI",',
'    dashLogoSubtitle: "शेतकरी डॅशबोर्ड",',
'    navHome: "होम",',
'    navContactUs: "संपर्क",',
'    navProfile: "प्रोफाइल",',
'    welcomeSubtitle:',
'      "तुमच्या शेतासाठी मदत हवी असल्यास खालील पर्यायांपैकी एक निवडा.",',
'    cardCropTitle: "पीक सुचवणी",',
'    cardCropText:',
'      "तुमच्या जमिनीच्या तपशीलावर आधारित 4–5 पिके आणि अंदाजित खर्च मिळवा.",',
'    cardMarketTitle: "तुमच्या भागातील बाजार मागणी",',
'    cardMarketText:',
'      "जवळच्या बाजारात चांगली मागणी आणि दर असलेली पिके पाहा.",',
'    cardChatTitle: "SAARTHI AI चॅटबॉक्स",',
'    cardChatText:',
'      "आमच्या बुद्धिमान सहाय्यकाला सोप्या भाषेत शेतीविषयी कोणतेही प्रश्न विचारा.",',
'    cardDiseaseTitle: "रोग ओळख",',
'    cardDiseaseText:',
'      "संभाव्य रोगांचा रिअल-टाइम शोध घेण्यासाठी पीक किंवा पानांचे फोटो अपलोड करा.",',
'    selectedCropTitle: "तुमचे निवडलेले पीक आणि मानीटरिंग",',
'    selectedCropIntro:',
'      "सुझावांमधून तुम्ही जे पीक निवडता, ते येथे दिसेल. त्याबरोबर साधे टाइमलाइन रिमाइंडरही दिसतील.",',
'    profileTitle: "प्रोफाइल (बेसिक डेमो)",',
'    contactUsTitle: "संपर्क",',
'    contactUsText: "शेताच्या मार्गदर्शनाबाबत काही प्रश्न किंवा मदतीसाठी, कृपया आमच्याशी संपर्क साधा.",',
'    currentCropLabel: "सध्याचे पीक:",',
'    chooseCropLabel: "पीक बदला:",',
'    playSelectedCropBtnText: "सध्याचे पीक वाचा",',
'    cardSelectedCropTitleSingular: "माझे निवडलेले पीक",',
'    cardSelectedCropTitlePlural: "माझी निवडलेली पिके",',
'    cardSelectedCropText: "तुमच्या निवडलेल्या पिकाची वेळ, खतांचे वेळापत्रक आणि पाणी देण्याच्या मार्गदर्शक तत्त्वांचा मागोवा घ्या."',
'  },',
'  ml: {',
'    dashLogoTitle: "SAARTHI",',
'    dashLogoSubtitle: "കർഷക ഡാഷ്ബോർഡ്",',
'    navHome: "ഹോം",',
'    navContactUs: "ബന്ധപ്പെടുക",',
'    navProfile: "പ്രൊഫൈൽ",',
'    welcomeSubtitle:',
'      "നിങ്ങളുടെ വയലിന് വേണ്ട സഹായം ലഭിക്കാൻ താഴെ കാണുന്ന ഓപ്ഷനുകളിൽ ഒന്നെന്തെങ്കിലും തിരഞ്ഞെടുക്കുക.",',
'    cardCropTitle: "വിള നിർദേശം",',
'    cardCropText:',
'      "നിങ്ങളുടെ ഭൂമിയുടെ വിവരങ്ങളുടെ അടിസ്ഥാനത്തിൽ 4–5 വിള നിർദേശംയും ബജറ്റ് കണക്കും നേടുക.",',
'    cardMarketTitle: "നിങ്ങളുടെ പ്രദേശത്തെ മാർക്കറ്റ് ഡിമാൻഡ്",',
'    cardMarketText:',
'      "അടുത്തുള്ള മാർക്കറ്റുകളിൽ നല്ല ഡിമാൻഡും വിലയും ഉള്ള വിളകൾ കാണുക.",',
'    cardChatTitle: "SAARTHI AI ചാറ്റ്ബോക്സ്",',
'    cardChatText:',
'      "ലളിതമായ ഭാഷയിൽ ഞങ്ങളുടെ ബുദ്ധിമാനായ അസിസ്റ്റൻ്റിനോട് കാർഷിക ചോദ്യങ്ങൾ ചോദിക്കുക.",',
'    cardDiseaseTitle: "രോഗ നിർണ്ണയം (ഡെമോ)",',
'    cardDiseaseText:',
'      "വിളയുടെയോ ഇലകളുടെയോ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്ത് സാധ്യതയുള്ള രോഗം കാണുക (ഡെമോ ലാജിക്ക്).",',
'    selectedCropTitle: "നിങ്ങൾ തെരഞ്ഞെടുത്ത വിളയും നിരീക്ഷണവും",',
'    selectedCropIntro:',
'      "നിർദേശങ്ങളിൽ നിന്ന് നിങ്ങൾ തിരഞ്ഞെടുത്ത വിള ഇവിടെ കാണിക്കും. ലളിതമായ ടൈംലൈൻ റിമൈൻഡറുകളും കാണും.",',
'    profileTitle: "പ്രൊഫൈൽ (ബേസിക് ഡെമോ)",',
'    contactUsTitle: "ബന്ധപ്പെടുക",',
'    contactUsText: "ഫാം മാർഗനിർദ്ദേശത്തെക്കുറിച്ചുള്ള എന്തെങ്കിലും ചോദ്യങ്ങൾക്കും പിന്തുണയ്ക്കും, ദയവായി ഞങ്ങളെ ബന്ധപ്പെടാൻ മടിക്കേണ്ടതില്ല.",',
'    currentCropLabel: "നിലവിലെ വിള:",',
'    chooseCropLabel: "വിള മാറ്റുക:",',
'    playSelectedCropBtnText: "നിലവിലെ വിള വായിക്കുക",',
'    cardSelectedCropTitleSingular: "ഞാൻ തിരഞ്ഞെടുത്ത വിള",',
'    cardSelectedCropTitlePlural: "ഞാൻ തിരഞ്ഞെടുത്ത വിളകൾ",',
'    cardSelectedCropText: "നിങ്ങൾ തിരഞ്ഞെടുത്ത വിളയുടെ സമയക്രമം, വളപ്രയോഗം, നനയ്ക്കൽ എന്നിവ ട്രാക്ക് ചെയ്യുക."',
'  }'
];
const newLines = [...lines.slice(0, 492), ...fixedLines, ...lines.slice(571)];
fs.writeFileSync('public/js/dashboard.js', newLines.join('\\n'));
console.log("Fixed dashboard.js");
